import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "@/components/Header/Header";
import { AppProvider } from "@/context/context";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${roboto.className}`}>
        <AppProvider>
          <div className='h-[2px] bg-gray-200'></div>
          <Header />
          <div className='h-[2px] bg-gray-200'></div>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
